version: '3.8'

services:
  db:
    image: postgres:16
    container_name: todolist-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"
    volumes:
      - ./db/script.sql:/docker-entrypoint-initdb.d/script.sql

  backend:
    build: ./server
    container_name: todolist-server
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: todolist

  frontend:
    image: nginx:alpine
    container_name: todolist-client
    volumes:
      - ./client:/usr/share/nginx/html
    ports:
      - "6969:80"
